### PR TITLE
CI: move the ghcr.io publish into the main action.

### PR DESCRIPTION
**Pull request by bloodearnest**
This serializes the publish to be able to use the auto-tagging steps so that we
can tag the docker image appropriately.

### CODE REVIEW

**Review by evansd — APPROVED** [review]

**Comment by sebbacon** [comment]
Sorry for only half-paying attention, and pretty sure I've asked this before, but why couldn't we use `whoan/docker-build-with-cache-action` for building and publishing?

**Comment by bloodearnest** [comment]
> Sorry for only half-paying attention, and pretty sure I've asked this before, but why couldn't we use `whoan/docker-build-with-cache-action` for building and publishing?

We possibly could, but a) wasn't sure it could publish to ghcr.io, and also wanted to try reduce dependency on external actions. 

That one in particular is complex.

**Comment by sebbacon** [comment]
The one thing I liked about it is the promise of caching, but makes sense!

**Comment by bloodearnest** [comment]
Right, I think caching of docker images in actions is the default now

**Pull request merged**
