### PR TITLE
Include non-ventilated patients in ICU results

### LINKED ISSUE #275: ICNARC function should not exclude non-ventilated patients
See discussion: https://github.com/opensafely/cohort-extractor/issues/273#issuecomment-679052963

Users need to be able to distinguish between ventilated and non-ventilated subgroups within ICNARC data.

We also need to consider which previous/current studies use ICNARC as an outcome and decide if they need to be re-run.

@HelenCEBM I think when I first made ICNARC I copied some code from a notebook you wrote without really thinking about why. Can you remember what the reason was for excluding patients without respiratory support in the first place? Just wondering if there was a reason to believe they were bad data.

### PR DESCRIPTION
**Pull request by evansd**
We have decided to ignore the value of the `Ventilator` column as we don't trust it. See discussion at:
https://github.com/opensafely/cohort-extractor/issues/275#issuecomment-685684964

Instead we use the counts for days of basic and advanced respiratory support (exact meaning of these tbc with ICNARC).

Returning options are now: `had_basic_respiratory_support`, `has_advanced_respiratory_support` and `had_respiratory_support` (which covers either case).

Closes #275

BREAKING CHANGE:
 1. Previously non-ventilated patients were excluded entirely from ICU results
 2. The `was_ventilated` returning option has been removed.

### CODE REVIEW

**Comment by evansd** [comment]
It occurs to me that my semver "breaking change" may push us from version 0 to version 1. Personally I don't care about this but I'm aware some people attach signalling value to version 1.0 and so I thought I should flag this up.

**Comment by sebbacon** [comment]
Looks good. Can you quickly search existing repos to check if any of them need changing to reflect this (and notify the author)? (I don't think they do).

> my semver "breaking change" may push us from version 0 to version 1

I think our decision to embrace semver inevitablly means we can no longer attach any romantic feelings to particular numbering systems.

**Comment by evansd** [comment]
Have messaged the channel and will await some response before merging.

**Comment by evansd** [comment]
Following discussion I'm going to do further work on this before merging. I think that now we've decided not to use the `Ventilator` column (because we don't trust it) we need to rename the `was_ventilated` returning value. I think we now need something like `had_basic_respiratory_support`, `had_advanced_respiratory_support`, and `had_respiratory_support` (to cover either case). Otherwise there's all sorts of potential for confusion.

**Review by sebbacon — APPROVED** [review]

**Pull request merged**
